apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: registry.cn-hangzhou.aliyuncs.com/bolawen/nginx:1.27.1-perl-linux-arm64
      ports:
        - containerPort: 80
      env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: config-map-data
              key: NAME
        - name: AGE
          valueFrom:
            configMapKeyRef:
              name: config-map-data
              key: AGE
      command: ["sh", "-c", "echo $NAME $AGE && nginx -g 'daemon off;'"]
