services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 9091:80
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
