apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: registry.cn-hangzhou.aliyuncs.com/bolawen/nginx:1.27.1-perl-linux-arm64
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-content
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-content
      hostPath:
        path: /data/nginx-content
        type: DirectoryOrCreate
