apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: registry.cn-hangzhou.aliyuncs.com/bolawen/nginx:1.27.1-perl-linux-arm64
      ports:
        - containerPort: 80
      env:
        - name: IP
          value: "192.168.0.0"
        - name: PORT
          value: "8080"
        - name: ADDR
          value: $(IP):$(PORT)
      command:
        [
          "sh",
          "-c",
          "echo The app is running in $ADDR && nginx -g 'daemon off;'",
        ]
