apiVersion: v1
kind: Service
metadata:
  name: test-headless-service
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: test-stateful-set-nginx
