apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      containers:
        - name: backend-server
          image: registry.cn-hangzhou.aliyuncs.com/bolawen/backend-server:1.0.3
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-server-config-map
                  key: APP_ENV
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-server-config-map
                  key: APP_PORT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-server-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: backend-server-logs-volume
              mountPath: /logs
            - name: backend-server-logrotate-config-volume
              mountPath: /etc/logrotate.d
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: backend-server-logs-volume
          persistentVolumeClaim:
            claimName: backend-server-logs-pvc
        - name: backend-server-logrotate-config-volume
          configMap:
            name: backend-server-logrotate-config-map
