apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      containers:
        - name: backend-server
          image: registry.cn-hangzhou.aliyuncs.com/bolawen/backend-server:1.0.1
          ports:
            - containerPort: 3000
          env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-server-config-map
                  key: APP_PORT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-server-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
