apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-server-logs-pv 
spec: 
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /mnt/logs


apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: backend-server-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      STORAGE: 5Gi