apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-server-logs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/logs
