apiVersion: v1
kind: Pod
metadata:
  name: test-pod-nfs1
spec:
  containers:
    - name: test-nginx-pod-nfs1
      images: xxx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nfs-content
          mountPath: /usr/share/nginx/html
  volumes:
