apiVersion: v1
kind: Pod
metadata:
  name: pod-nfs
spec:
  containers:
    - name: nginx-pod-nfs
      image: registry.cn-hangzhou.aliyuncs.com/bolawen/nginx:1.27.1-perl-linux-arm64
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nfs-content
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nfs-content
      nfs:
        server: master
        path: /mnt/nfs_share
