services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: node:latest
    networks:
      - backend
      - frontend

  nginx:
    image: nginx:latest
    ports:
      - 9091:80
    depends_on:
      - node
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./var/log/nginx:/var/log/nginx
    networks:
      - frontend

networks: backend
  frontend
