apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test-nginx
spec:
  selector:
    app: test-nginx
  type: NodePort
  ports:
    - port: 80
      name: nginx-server
      protocol: TCP
      targetPort: 80
      nodePort: 30001
