apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stateful-set
spec:
  serviceName: "mysql-head-less-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: registry.cn-hangzhou.aliyuncs.com/bolawen/mysql:9.0.1-linux-arm64
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
            - name: mysql-config-map-volume
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: mysql-config-map-volume
          configMap:
            name: mysql-config-map
  volumeClaimTemplates:
    - metadata:
        name: mysql-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
