services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node1
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - node1
  node2:
    image: node:latest
    container_name: node2
    depends_on:
      node1:
        condition: service_healthy
    networks:
      - node1

networks:
  node1:
    driver: bridge
