services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: node:latest
    networks:
      - backend
      - frontend

  nginx:
    image: nginx:latest
    ports:
      - 9090:80
    depends_on:
      - node
    volumes:
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    networks:
      - frontend

networks:
  backend:
  frontend:
